home.title=V\u00EDtejte v Underflow!
home.date=Datum
home.action.here=Zde!
home.securedPage=Zabezpe\u010Den\u00E1 str\u00E1nka
home.openAPIDocs=OpenAPI dokumentace
home.routingTestPage=Testovac\u00ED str\u00E1nka sm\u011Brov\u00E1n\u00ED
home.chunkTestPage=Dlouh\u00E1 str\u00E1nka s v\u00EDce \u010D\u00E1stmi (HTTP)
home.assetsTestPage=Na\u010D\u00EDt\u00E1n\u00ED prost\u0159edk\u016F z Java Resources
home.exceptionTestPages=DEV v\u00FDjimky
home.exceptionTestPages.java=Java v\u00FDjimka!
home.exceptionTestPages.ftl=FTL v\u00FDjimka!
home.exceptionTestPages.javaInFtl=Java v\u00FDjimka v FTL!
home.languageSelection=Zm\u011Bnit jazyk
home.languageSelection.french=Francouz\u0161tina
home.languageSelection.english=Angli\u010Dtina
home.languageSelection.czech=\u010Ce\u0161tina
home.languageSelection.deleteCookie=Smazat jazykov\u00FD cookie
home.stopServer=Zastavit webov\u00FD server
home.userData=U\u017Eivatelsk\u00E1 data
home.userData.langCookie=Jazykov\u00FD cookie
home.userData.langUsed=Pou\u017E\u00EDvan\u00FD jazyk
home.userData.logout=Odhl\u00E1sit se
home.userData.username=U\u017Eivatelsk\u00E9 jm\u00E9no
home.userData.scopes=Rozsahy
home.userData.notConnected=Nep\u0159ipojeno
home.userData.getForm=GET p\u0159ihla\u0161ovac\u00ED formul\u00E1\u0159
home.userData.postForm=POST p\u0159ihla\u0161ovac\u00ED formul\u00E1\u0159
home.userData.form.name=Jm\u00E9no
home.userData.form.scopes=Rozsahy (web vy\u017Eadov\u00E1n pro p\u0159\u00EDstup k zabezpe\u010Den\u00E9 str\u00E1nce):