home.title=Welcome to Underflow !
home.date=Date
home.action.here=Here !
home.securedPage=Secured page
home.openAPIDocs=OpenAPI Docs
home.routingTestPage=Routing test page
home.chunkTestPage=Long page with multiple chunk (HTTP)
home.assetsTestPage=Assets loading from Java Resources
home.exceptionTestPages=DEV exceptions
home.exceptionTestPages.java=Java exception !
home.exceptionTestPages.ftl=FTL exception !
home.exceptionTestPages.javaInFtl=Java exception in FTL !
home.languageSelection=Change language
home.languageSelection.french=French
home.languageSelection.english=English
home.languageSelection.czech=Czech
home.languageSelection.deleteCookie=Delete language cookie
home.stopServer=Stop the web server
home.userData=User data
home.userData.langCookie=Language cookie
home.userData.langUsed=Language used
home.userData.logout=Logout
home.userData.username=Username
home.userData.scopes=Scopes
home.userData.notConnected=Not connected
home.userData.getForm=GET Login form
home.userData.postForm=POST Login form
home.userData.form.name=Name
home.userData.form.scopes=Scopes (web required to access secured page):
