home.title=Bienvenu sur Underflow !
home.date=Date
home.action.here=Ici !
home.securedPage=Page sécurisée
home.openAPIDocs=Documentation OpenAPI
home.routingTestPage=Page de test de routage
home.chunkTestPage=Page longue avec plusieurs "chunk" (HTTP)
home.assetsTestPage=Chargement des ressources depuis les ressources Java
home.exceptionTestPages=Exceptions DEV
home.exceptionTestPages.java=Exception Java !
home.exceptionTestPages.ftl=Exception FTL !
home.exceptionTestPages.javaInFtl=Exception Java dans FTL !
home.languageSelection=Changer de langue
home.languageSelection.french=Français
home.languageSelection.english=Englais
home.languageSelection.deleteCookie=Supprimer le cookie de langue
home.stopServer=Arrêter le serveur web
home.userData=Données utilisateur
home.userData.langCookie=Cookie de langue
home.userData.langUsed=Langue utilisée
home.userData.logout=Déconnexion
home.userData.username=Nom d'utilisateur
home.userData.scopes=Scopes
home.userData.notConnected=Non connecté
home.userData.getForm=Formulaire de connexion GET
home.userData.postForm=Formulaire de connexion POST
home.userData.form.name=Nom
home.userData.form.scopes=Scopes (web requis pour accéder à la page sécurisée) :
